name: mafia_tutorial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  drop_cap_text: ^1.1.3
  dropdown_button2: ^2.3.9
  lorem_ipsum: any
  provider: ^6.0.0
  xml: any

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/data/mafia_roles.xml
    - assets/data/citizens_roles.xml
    - assets/data/independent_roles.xml
    - assets/
    - assets/data/idioms.txt
    - assets/data/morals.txt
    - assets/data/rules.txt
    - assets/images/
    - assets/images/roles/
    - assets/images/roles/default_role_picture.jpg
